### PR TITLE
setting test jvm maximum memory

### PR DESCRIPTION
**Pull request by lbergelson**
this seems to fix the travis failures

[Review on Reviewable](https://reviewable.io/reviews/broadinstitute/hellbender-protected/186)

### CODE REVIEW

**Comment by lbergelson** [comment]
@davidbenjamin This should hopefully fix the travis out of memory failures.

**Comment by lbergelson** [comment]
@davidbenjamin @samuelklee I think this will fix your travis situation.  Could you someone give this a quick glance?

**Comment by samuelklee** [comment]
thanks, @lbergelson!

**Comment by lbergelson** [comment]
We're following a similar problem in gatk main.  We've seen an oom failure in gatk just now despite this fix.  Hopefully this will at least improve the situation though...

**Comment by samuelklee** [comment]
yeah, looks like we are still getting some oom messages---although fewer than before?

**Comment by lbergelson** [comment]
the joys of transient errors

**Pull request merged**
